#!/bin/bash

#FILE:  xpm2gif
#DATE:  05 AUG 2012
#AUTH:  G. E. Deschaines
#DESC:  Converts a sequence of XPM files to GIF files and merges
#       the GIF files into an animated GIF file.

#NOTE:  Requires the ImageMagick convert program.

# Get list of XPM files.

XPM_LIST=(`ls *.xpm`)
if [ "${#XPM_LIST[*]}" == "0" ]
then
  echo "error:  No XPM files in present working directory."
  exit -1
fi

# Convert each XMP file into a GIF file.

GIF_LIST=""
for FILE in ${XPM_LIST[@]}
do
  NAME=${FILE%.xpm}
  echo "converting:  $FILE"
  convert $FILE $NAME.gif
  GIF_LIST="$GIF_LIST $NAME.gif"
done

# Merge all GIF files into the animated gif file.

echo "Creating animated gif file:  img_anim.gif"
convert -dispose None -delay 4 $GIF_LIST -loop 5 img_anim.gif

exit 0
